=== mattschwartz/stonequest-original/stonequest/src/com/barelyconscious/xml/entities.xsd
<?xml version="1.0"?>

<!-- Reference

http://arianne.cvs.sf.net/viewvc/arianne/stendhal/data/conf/creatures.xsd?view=markup

-->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Define simple types -->
    <xs:element name="description" type="xs:string" />
    <xs:element name="experience" type="xs:double" />
    <xs:element name="faction" type="xs:integer" />

    <!-- Simple types for complex type, attributes -->
    <xs:element name="health" />
    <xs:element name="strength" />
    <xs:element name="accuracy" />
    <xs:element name="defense" />
    <xs:element name="evasion" />
    <xs:element name="fireMagicBonus" />
    <xs:element name="frostMagicBonus" />
    <xs:element name="holyMagicBonus" />
    <xs:element name="chaosMagicBonus" />
    <xs:element name="faithMagicBonus" />

    <xs:attribute name="value" type="xs:double" />
    <xs:attribute name="quantity" type="xs:string" />
    <xs:attribute name="probability" type="xs:double" />
    
    <!-- Definition of complex types -->
    <xs:element name="attributes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="health" />
                <xs:element ref="strength" />
                <xs:element ref="accuracy" />
                <xs:element ref="defense" />
                <xs:element ref="evasion" />
                <xs:element ref="fireMagicBonus" />
                <xs:element ref="frostMagicBonus" />
                <xs:element ref="holyMagicBonus" />
                <xs:element ref="chaosMagicBonus" />
                <xs:element ref="faithMagicBonus" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Item element -->
    <xs:element name="item">
        <xs:complexType>
            <xs:attribute name="type" type="xs:string" />
            <xs:attribute name="id" type="xs:integer" />
            <xs:attribute name="level" type="xs:double" />
            <xs:attribute ref="quantity" />
            <xs:attribute ref="probability" />
        </xs:complexType>
    </xs:element>
    
    <!-- Drop element, defined as any numer of Item elements -->
    <xs:element name="drop">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="item" maxOccurs="unbounded" />
            </xs:sequence>
            
            <xs:attribute ref="quantity" />
            <xs:attribute ref="probability" />
        </xs:complexType>
    </xs:element>
    
    <!-- LootTable element, defined as any number of Drop elements -->
    <xs:element name="lootTable">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="drop" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Each entity has a class -->
    <xs:element name="class">
        <xs:complexType>
            <xs:attribute name="style" type="xs:string" />
            <xs:attribute name="damageType" type="xs:string" />
            <xs:attribute name="tileId" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    <!-- A single entity definition -->
    <xs:element name="entity">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="class" />
                <xs:element ref="description" />
                <xs:element ref="experience" />
                <xs:element ref="faction" />
                <xs:element ref="attributes" />
            </xs:sequence>
            
            <xs:attribute name="id" type="xs:integer" />
            <xs:attribute name="name" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    <!-- Encompasses many entity definitions -->
    <xs:element name="entities">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entity" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mattschwartz/stonequest-original/stonequest/src/com/barelyconscious/xml/entities.xml
<?xml version="1.0" ?>

<!-- Reference

http://arianne.cvs.sf.net/viewvc/arianne/stendhal/data/conf/creatures/elf.xml?view=markup

-->

<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="entities.xsd">
    <entity id="0" name="Sewer Rat">
        <class style="short range" damageType="melee" tileId="SewerRat.png" />
        
        <description>A filthy rat that has crawled out from an unknown location to ruin your day.</description>
        <experience>12</experience>
        <faction>0</faction>
        <!-- <corpse description="Rotting away..." /> -->

        <attributes>
            <health value="1.3" />
            <strength value="0.75" />
            <accuracy value="1" />
            <defense value="0" />
            <evasion value="0" />
            <fireMagicBonus value="0" />
            <frostMagicBonus value="0" />
            <holyMagicBonus value="0" />
            <chaosMagicBonus value="0" />
            <faithMagicBonus value="0" />
        </attributes>

        <lootTable>
            <drop quantity="[1,1]" probability="100.0">
                <item type="gold" id="0" quantity="[3,15]" probability="100.0" />
            </drop>
            
            <drop quantity="[0,2]" probability="36.0">
                <item type="potion" id="7" level="1" quantity="[1,1]" probability="2.0" />
                <item type="scroll" id="8" level="0" quantity="[1,1]" probability="3.0" />
                <item type="food" id="9" level="1" quantity="[1,1]" probability="15.0" />
                <item type="projectile" id="10" level="0" quantity="[1,15]" probability="13.4" />
            </drop>

            <drop quantity="[0,1]" probability="12.0">
                <item type="weapon" id="1" level="1" quantity="[1,1]" probability="16.67" />
                <item type="weapon" id="2" level="1" quantity="[1,1]" probability="8.0" />
                <item type="weapon" id="3" level="1.3" quantity="[1,1]" probability="0.1" />
                <item type="armor" id="4" level="1" quantity="[1,1]" probability="16.67" />
                <item type="armor" id="5" level="1" quantity="[1,1]" probability="8.0" />
                <item type="armor" id="6" level="1" quantity="[1,1]" probability="8.0" />
            </drop>
        </lootTable>
    </entity>
</entities>
